### ISSUE TITLE
missing dayjs module in develop branch

### ISSUE THREAD

**Issue by pintux** [sebbo2002/ical-generator#234]
I've installed version 2.0.0-develop.2 in a TypeScript project. At compile time, on my project, I'm getting:

```
node_modules/ical-generator/dist/types.d.ts:3:23 - error TS2307: Cannot find module 'dayjs' or its corresponding type declarations.

3 import { Dayjs } from 'dayjs';

Found 1 error.
```

**Comment by pintux** [comment]
Using `2.0.0-develop.8` version I'm getting the following errors:

`node_modules/ical-generator/dist/event.d.ts:1:28 - error TS2307: Cannot find module 'rrule' or its corresponding type declarations.

1 import type { RRule } from 'rrule';
                             ~~~~~~~

node_modules/ical-generator/dist/types.d.ts:3:28 - error TS2307: Cannot find module 'dayjs' or its corresponding type declarations.

3 import type { Dayjs } from 'dayjs';
                             ~~~~~~~


Found 2 errors.`

**Comment by sebbo2002** [comment]
Oh crap, how stupid of me. I'll take care of it tonight.

**Comment by sebbo2002** [comment]
Okay, thought I forgot to add the `type` flag for `RRule`, but that's not the issue. I tested it locally, it works for me. Do you use typescript >= 3.8? The type only imports are introduced in this version…

<img width="544" alt="Bildschirmfoto 2021-03-24 um 20 05 05" src="https://user-images.githubusercontent.com/812398/112369222-3da74c00-8cdc-11eb-979e-71928c145546.png">

**Comment by pintux** [comment]
I'm using TypeScript 3.9.9 and (now) `ical-generator` version `^2.0.0-develop.14"`.

`> tsc -v && tsc

Version 3.9.9
node_modules/ical-generator/dist/event.d.ts:1:28 - error TS2307: Cannot find module 'rrule' or its corresponding type declarations.

1 import type { RRule } from 'rrule';
                             ~~~~~~~

node_modules/ical-generator/dist/types.d.ts:3:28 - error TS2307: Cannot find module 'dayjs' or its corresponding type declarations.

3 import type { Dayjs } from 'dayjs';
                             ~~~~~~~


Found 2 errors.`

I will try with a clean project

**Comment by sebbo2002** [comment]
Okay, I have now been able to reproduce the whole thing. Apparently, the dependencies must still be present when compiling in order to be able to check the types. Even if you use [type-only imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export). This is of course very annoying. I would put the dependencies in `optionalDependencies`, then they are usually installed automatically (if not already done). And since they will no longer be in the JavaScript, there should be no issue with this solution. I will do this in the next few days, but I don't have the time now.

**Comment by sebbo2002** [comment]
Okay, I have now packed the supported external libraries into `peerDependencies`. This way they should always be installed with npm 7. I hope this solves the problem. `peerDependencies` are installed with npm@7, before that you have to install them manually. I will add to the FAQ accordingly.
