### ISSUE TITLE
HTML in event descriptions

### ISSUE THREAD

**Issue by ehynds** [sebbo2002/ical-generator#323]
Hi, thanks for the great library.

I noticed that ical-generator [escapes all quote characters](https://github.com/sebbo2002/ical-generator/blob/7e7eb623cd42e80bff4eaa68172e6dbdb13b1da2/src/tools.ts#L119-L120) even inside event descriptions, which results in invalid HTML.

Given a simple description value of:

```html
<p><a href="http://google.com" rel="noopener noreferrer" target="_blank">Google.com</a></p>
```

The result after running through `createEvent` is:

```js
description: '<p><a href=\\http://google.com\\ rel=\n' +
  'oopener noreferrer\\ target=\\_blank\\>Google.com</a></p>',
```

What is the proper guidance for using descriptions with HTML?

Thanks!

**Comment by sebbo2002** [comment]
Use an object with `plain` and `html` key to specify both a text and an HTML description. The interface for this is [documented here](https://sebbo2002.github.io/ical-generator/develop/reference/interfaces/ICalDescription.html).

### Example

```js
const calendar = ical({
    events: [{
        id: 'Test',
        start: new Date('2020-08-13T00:00:00-05:00'),
        stamp: new Date('2020-08-13T00:00:00-05:00'),
        summary: 'Example Event',
        description: {
            plain: 'Google.com (https://google.com)',
            html: '<p><a href="https://google.com" rel="noopener noreferrer" target="_blank">Google.com</a></p>'
        }
    }]
});

console.log(calendar.toString());
```

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//sebbo.net//ical-generator//EN
BEGIN:VEVENT
UID:Test
SEQUENCE:0
DTSTAMP:20200813T050000Z
DTSTART:20200813T050000Z
SUMMARY:Example Event
DESCRIPTION:Google.com (https://google.com)
X-ALT-DESC;FMTTYPE=text/html:<p><a href=\"https://google.com\" rel=\"noope
 ner noreferrer\" target=\"_blank\">Google.com</a></p>
END:VEVENT
END:VCALENDAR
```

**Comment by oceansam** [comment]
@sebbo2002 

Would like to note that replicating the code provided above returned a a object as the description instead of the rendered content. May I know what version of the package would this feature be excluded from?

`"ical-generator": "^1.15.0",`

```js
const calendar = ical({
    events: [{
        id: 'Test',
        start: new Date('2020-08-13T00:00:00-05:00'),
        stamp: new Date('2020-08-13T00:00:00-05:00'),
        summary: 'Example Event',
        description: {
            plain: 'Google.com (https://google.com)',
            html: '<p><a href="https://google.com" rel="noopener noreferrer" target="_blank">Google.com</a></p>'
        }
    }]
});

console.log(calendar.toString());
```
Returned me, 

![image](https://user-images.githubusercontent.com/56453957/141837565-d49ea8d8-4747-4945-b76e-426f520dc163.png)

**Comment by sebbo2002** [comment]
Oh man, you should update. Is there any reason not to use the current version? 

The above behaviour applies for v2.0.0 and later. Before that, there was an `htmlDescription()` method for HTML descriptions. I can't tell you exactly when this method was added, though, since I only support the current major version.

**Comment by oceansam** [comment]
Thanks for the fast reply, and gotcha that would make sense. I'll look for bumping the package up. Appreciate it!
