### ISSUE TITLE
How to make the the browser to download the file

### ISSUE THREAD

**Issue by noushka86** [sebbo2002/ical-generator#41]
I dont understand what to do after creating the event object. 
how to I save it as a ics file and make the browser download it?
sorry, I'm new...

**Comment by takkaria** [comment]
Once you have your calendar object, if you have a node HTTP response object, you can call <calendar objejct>.serve(<response object>).  e.g.

```
function(req, res) {
  let cal = ical(...);
  cal.createEvent(...);
  cal.serve(res);
}
```

This sets the correct HTTP headers for the content type as well as a 'Content-Disposition: attachment' header which tells the browser it should download it instead of showing it.

**Comment by avitaldrucker** [comment]
@takkaria This does not work for me. I'm creating and serving the calendar on the backend and when I call the route on the frontend, nothing is downloaded. My backend code:
```js
someRouter.post('/events', function(req, res) {
  const cal = ical()
  cal.createEvent({
    start: Date(),
    end: Date(),
    timestamp: Date(),
    summary: 'my event', organizer: 'Sebastian Pekarek <mail@example.com>'
  })
  cal.serve(res)
})
```
My frontend in React using Fetch:
`const res = await (await post('no-excuses/events'))`

**Comment by takkaria** [comment]
I haven't used this library for a couple of years or needed to force downloads, but the way a server can trigger a download is by setting the `Content-Disposition` header to `attachment`.  ical-generator does this, so your problem is really that `fetch()` does not respond to that header. 
 Googling [`fetch() content-disposition attachment`](https://www.google.co.uk/search?q=fetch()+content-disposition+attachment) brought up the following page you might find useful:

https://stackoverflow.com/questions/37095233/downloading-and-saving-data-with-fetch-from-authenticated-rest
