### ISSUE TITLE
TypeError: ical is not a function

### ISSUE THREAD

**Issue by Vivek377** [sebbo2002/ical-generator#545]
Hey, I'm trying to generate calendar invite object. using ical-generator, but I get this error that ical is not a function. here's my code snippet.
``` js
const ical = require('ical-generator');
const getIcalObjectInstance = (starttime, endtime, summary, description, location, url, name, email) => {
    const cal = ical({ name: 'my first iCal' });
    cal.createEvent({
        start: starttime,
        end: endtime,
        summary: summary,
        description: description,
        location: location,
        url: url,
        organizer: {
            name: name,
            email: email,
        },
    });
    return cal;
}
```
when the function getIcalObjectInstance is invoked I get the error.

**Comment by sebbo2002** [comment]
Hello @Vivek377, ical-generator is delivered as ESM module since version 4.0, see [release notes](https://github.com/sebbo2002/ical-generator/releases/tag/v4.0.0). If you use `const { default: ical } = require('ical-generator');` or `const ical = require('ical-generator').default;` instead, it should work. If not, please reopen the ticket with your detailed error description.
