### ISSUE TITLE
Versioning is confusing and not user-friendly

### ISSUE THREAD

**Issue by titanism** [sebbo2002/ical-generator#566]
Right now the default branch is `develop`, which has a `package.json` file pointing at an extremely old version <https://github.com/sebbo2002/ical-generator/blob/49e4a4c355651fe8c3d3bc7dea053d8268f8195d/package.json#L128>.

Additionally, there's so many different versions in npm as well.  This is extremely confusing for end-users.
<img width="797" alt="Screen Shot 2024-02-06 at 11 17 16 AM" src="https://github.com/sebbo2002/ical-generator/assets/101466223/20c93f29-c4e9-4f21-9073-be6ef1f4d569">

No change logs can be easily found either.  We suggest that you start using np to publish releases (which will automate all of the releases in GitHub Releases tab as well as provide a list of commits since the last publish.  This should also dummy-proof the publishing process to npm on your side.  See <https://github.com/sindresorhus/np>.

Please set a better default branch that mirrors the latest from npm, and it would be great to clean-up the versioning and `package.json` files, as well as branches in this repo if possible.

Thank you :pray:

**Comment by sebbo2002** [comment]
> Right now the default branch is `develop`, which has a `package.json` file pointing at an extremely old version

I can partially understand that with the `package.json`. I'll add this to my todo list for non-development releases, but I won't give it high priority, as the current version can be viewed at any time on GitHub or npm. It's just a nice to have.


> Additionally, there's so many different versions in npm as well. This is extremely confusing for end-users.

Can you explain why it should be confusing that there are many versions? This library is maintained, of course there are many versions over time? I doubt many people look at the list of versions and even if I stopped building the `develop` versions (which I won't do) this list would be very long. As long as there are the two channels `latest` and `next` (as can be seen on your screenshot), the latest stable version is automatically installed as long as you do not explicitly call `npm i ical-generator@next`.


> No change logs can be easily found either.

As with many popular libraries, the changelog can be found in [`CHANGELOG.md`](https://github.com/sebbo2002/ical-generator/blob/develop/CHANGELOG.md). The individual releases on GitHub have also documented the changes ([example](https://github.com/sebbo2002/ical-generator/releases/tag/v6.0.1)).


> We suggest that you start using np to publish releases (which will automate all of the releases in GitHub Releases tab as well as provide a list of commits since the last publish. This should also dummy-proof the publishing process to npm on your side. See [sindresorhus/np](https://github.com/sindresorhus/np).

I use semantic-release for that. So it's already automated. Please let me know what you are missing.


> Please set a better default branch that mirrors the latest from npm, and it would be great to clean-up the versioning and `package.json` files, as well as branches in this repo if possible.

- The default branch currently mirrors the `next` channel to npm. This is intentional and as long as there are no concrete reasons against it, I would leave it that way. No law says that npm `latest` should / must mirror the standard branch 1:1.
- I don't see any concrete suggestions for versioning other than "use a different tool", but I'd be happy to elaborate further.
- There are three branches in this repo and all are current and in use

So please elaborate on your points again, otherwise I would close this issue as a nonsense ticket. Because no objective issues have been raised here.

**Comment by sebbo2002** [comment]
I already agreed with you about the `package.json`. I'm talking about the other points. What exactly is disorganized? What would you change specifically? Please make a detailed list with concrete things or a direct pull request. Because I can't follow you there at the moment.

**Comment by sebbo2002** [comment]
This is not correct, GitHub releases are currently added for each version by semantic-release. Have a look at `v6.0.1` or another stable version. The fact that the develop / next versions usually have no changelog is due to the fact that usually only dependencies have been changed / updated. These are not explicitly listed in the changelogs, but can be tracked via the respective merge requests (e.g. https://github.com/sebbo2002/ical-generator/pull/556).

Any other issues (besides the outdated package.json) that lead to the "very disorganized" repository in your eyes?

**Comment by sebbo2002** [comment]
Okay, with [this commit](https://github.com/sebbo2002/ical-generator/commit/c6d2f1f9909930743acb54003e124faea4f58cec) I have now ensured that the package.json is always up-to-date. I hope this solves your problems. Please remember that changes will not be made until the next release.

In future, I would ask you to check whether the tone is really appropriate before submitting your issues. Most open source projects are maintained and supported free of charge by volunteer developers. A friendly tone would be very appropriate, especially if at the end of the day only one of many points remains. Because to be honest, I still can't quite understand how an old version in the `package.json` deserves descriptions like "confusing", "not user-friendly" or "super bad impression at first".
